Cycle de vie
ansforge/CISIS-doctrine-gouvernance pull request #1
Opened 2024-07-16 15:16 UTC by nriss

2024-07-19 14:58 UTC, nriss commented on docs/pages/docs/cycle-de-vie.md
> +Ces travaux se sont inspirés des pratiques internationales au niveau d'[IHE](https://wiki.ihe.net/index.php/Process) et de [HL7](ttps://confluence.hl7.org/display/FHIR/FHIR+Maturity+Model
Il manque le H

2024-08-13 08:59 UTC, jccauvin requested changes

2024-08-13 08:59 UTC, jccauvin commented on docs/pages/docs/cycle-de-vie.md
> +Il a été identifié qu'il n'est pas évident pour les développeurs de solutions d'identifier si la spécification est de qualité et de maturité suffisante pour pouvoir être implémentée en production san
```suggestion
Le niveau de qualité et la maturité des volets du CI-SIS et des guides d’implémentation sont des informations importantes qui vont inciter les éditeurs de solution à engager des développements sans craindre de futures évolutions majeures.
```

2024-08-13 09:13 UTC, nriss commented
Utiliser des doubles quotes partout pour définir les statuts

2024-08-13 16:02 UTC, jccauvin requested changes

2024-08-14 08:33 UTC, nriss commented on docs/pages/docs/cycle-de-vie.md
> +Ce stade est atteint lorsque la spécification a déjà été mise en œuvre dans un projet national ou testée lors d'un projectathon. La spécification a eu des retours post-concertation, post-projectathon
Je suis pas d'accord avec le terme "déploiement", pour moi implémentation correspond au fait de prendre les specs et à développer l'API correspondante, alors que déploiement correspond à la publication de l'API sur le serveur de production

J'ai mis "mise en oeuvre"

2024-08-14 12:48 UTC, jccauvin commented on docs/pages/docs/cycle-de-vie.md
> +Ce stade est atteint lorsque la spécification a déjà été mise en œuvre dans un projet national ou testée lors d'un projectathon. La spécification a eu des retours post-concertation, post-projectathon
Les questions à se poser sont : 

- Quelles sont les statuts qui déclenchent le déploiement d'une spécification dans un environnement de production (serveur d'API FHIR, interface HL7 V2 ...) ?  "trial" ? "final" ?
- Quel est le statut minimal d'une spécification pour qu'elle soit référencée dans un programme national (homologation Ségur, certification des DMN ...) ? "trial" ? "final" ?

Le passage par un ou plusieurs projectathons  permet à une spécification d'atteindre le statut "final". Mais pour le Ségur V2, le volet "Transmission au LPS de documents CDA provenant d'un courriel MSSanté" n'est pas passé par la case projectathon et a donc un statut "trial". Le volet est pourtant référencé dans le Ségur V2 et l'ANS publiera des évolutions mineures et des corrections au fil de l'eau quand cette spécification sera développée et mise en production. Donc tout n'est pas blanc ou noir. C'est pour cette raison que j'ai mis que le statut "final" pouvait aussi être atteint après une mise en oeuvre/déploiement d'une spécification dans un environnement de production. Dans ce contexte, mise en oeuvre = déploiement.

2024-08-19 12:45 UTC, nriss commented
Proposition de changements JCC  sur les noms de statuts à discuter :

- brouillon devient version-de-travail 
- en-concertation devient version-en-concertation
- pour-implementation devient version-pour-mise-en-oeuvre
- final-text devient version-finale

2024-08-23 13:05 UTC, nriss commented on docs/pages/docs/cycle-de-vie.md
> +Les auteurs de la spécification ont estimé qu'elle avait atteint le **stade de maturité le plus élevé**.
Je marque ça comme résolu, je vois pas le problème

2024-10-11 13:23 UTC, merged